spring:
  profiles:
    active: dev  # Pode ser alterado para 'prod' em produção

  application:
    name: wallets-service


  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: postgres
    password: Pos@2025app
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
